
-- 유저 테이블 -- 
CREATE TABLE USERLIST(
USER_NO NUMBER PRIMARY KEY, -- 사용자 NO
USER_NICKNAME VARCHAR2(50) NOT NULL, -- 닉네임  
USER_AGE NUMBER NOT NULL, -- 나이 
USER_EMAIL VARCHAR2(50) NOT NULL CONSTRAINT EMAIL_UNI UNIQUE, -- 이메일 
USER_GENDER VARCHAR2(3) NOT NULL, -- 성별
USER_GRADE VARCHAR2(10) DEFAULT '일반' NOT NULL, -- 유저등급(일반/홀릭/관리자) 
USER_POINT NUMBER DEFAULT 0 NOT NULL, -- 포인트 
USER_PREFER VARCHAR2(100), -- 선호취향
USER_ATTEND NUMBER DEFAULT 0 NOT NULL, --출석체크
USER_BLACK NUMBER DEFAULT 0 NOT NULL, --블랙컨슈머
USER_USAGE NUMBER DEFAULT 1 NOT NULL --사용여부(1 사용, 0 비사용)
); 

CREATE SEQUENCE USER_NO_SEQ NOCACHE;
DROP SEQUENCE USER_NO_SEQ;

INSERT INTO USERLIST VALUES(USER_NO_SEQ.NEXTVAL, '메론', 20, 'aaa@naver.com', '남', '일반', 0, '한식',0,1,1);
INSERT INTO USERLIST VALUES(USER_NO_SEQ.NEXTVAL, '관리자', 30, 'ma@naver.com', '여', '관리자', 0, '양식',2,0,1);

SELECT * FROM USERLIST;

DROP TABLE USERLIST;



-- 식당 테이블 -- 
CREATE TABLE RESTAURANT(
RES_NO NUMBER PRIMARY KEY, -- 식당 NO
RES_NAME VARCHAR2(50) NOT NULL, -- 식당 이름
RES_PLACE VARCHAR2(100) NOT NULL, -- 식당 위치  
RES_TEL VARCHAR2(50), -- 식당 번호 
RES_TYPE VARCHAR2(50) NOT NULL, -- 식당 종류 
RES_PHOTO VARCHAR2(300),
RES_HITS NUMBER DEFAULT 0 NOT NULL, -- 식당 조회수 
RES_GRADE NUMBER NOT NULL, -- 식당 등급 
RES_PRICE VARCHAR2(30) NOT NULL -- 식당 가격대 
);

CREATE SEQUENCE RES_NO_SEQ NOCACHE;
DROP SEQUENCE RES_NO_SEQ;

INSERT INTO RESTAURANT VALUES(RES_NO_SEQ.NEXTVAL, '냠냠', '강남', '02-111-1111', '한식', '', 0, 4, '3만원대');
INSERT INTO RESTAURANT VALUES(RES_NO_SEQ.NEXTVAL, '맛집', '강동', '02-111-1111', '한식', '', 0, 3, '2만원대');
INSERT INTO RESTAURANT VALUES(RES_NO_SEQ.NEXTVAL, '먹고싶다', '강동', '02-111-1111', '양식', '', 0, 4, '5만원대');

SELECT * FROM RESTAURANT;

DROP TABLE RESTAURANT;



-- 찜 테이블 -- 
CREATE TABLE BOOKMARK(
BOOKMARK_NO NUMBER PRIMARY KEY, -- 찜 넘버 
USER_NO NUMBER REFERENCES USERLIST(USER_NO) ON DELETE CASCADE, -- 유저 NO
RES_NO NUMBER REFERENCES RESTAURANT(RES_NO) ON DELETE CASCADE -- 식당 NO 
);

CREATE SEQUENCE BOOKMARK_NO_SEQ NOCACHE;
DROP SEQUENCE BOOKMARK_NO_SEQ;

INSERT INTO BOOKMARK VALUES(BOOKMARK_NO_SEQ.NEXTVAL, 1, 1);

DROP TABLE BOOKMARK;




-- 메뉴 테이블 --
CREATE TABLE MENU(
MENU_NO NUMBER PRIMARY KEY, -- 메뉴 NO 
RES_NO NUMBER REFERENCES RESTAURANT(RES_NO) ON DELETE CASCADE, -- 식당 NO 
MENU_NAME VARCHAR2(50) NOT NULL, -- 메뉴 이름 
MENU_PRICE VARCHAR2(30) NOT NULL -- 메뉴 가격 
);

CREATE SEQUENCE MENU_NO_SEQ NOCACHE;
DROP SEQUENCE MENU_NO_SEQ;

INSERT INTO MENU VALUES(MENU_NO_SEQ.NEXTVAL, 1, '계란찜', '5000원');

SELECT * FROM MENU;

DROP TABLE MENU;


-- 리뷰 테이블 --
CREATE TABLE REVIEW(
REVIEW_NO NUMBER PRIMARY KEY, -- 리뷰 NO
RES_NO NUMBER REFERENCES RESTAURANT(RES_NO) ON DELETE CASCADE, -- 식당 NO 
USER_NO NUMBER REFERENCES USERLIST(USER_NO) ON DELETE CASCADE, --유저NO
REVIEW_HITS NUMBER DEFAULT 0 NOT NULL, -- 리뷰 조회수 
REVIEW_GRADE NUMBER NOT NULL, -- 평점 (식당에 평점 몇점 주눈지?) 
REVIEW_PHOTO VARCHAR2(100), -- 사진 .... 
REVIEW_CONTENT VARCHAR2(500) NOT NULL, -- 리뷰 내용 
REVIEW_DATE DATE DEFAULT SYSDATE, -- 리뷰 작성날짜 
REVIEW_AGREE NUMBER NOT NULL -- 리뷰 공감수 
);

CREATE SEQUENCE REVIEW_NO_SEQ NOCACHE;
DROP SEQUENCE REVIEW_NO_SEQ;

INSERT INTO REVIEW VALUES(REVIEW_NO_SEQ.NEXTVAL, 1, 1, 0, 4, '', '맛있당', SYSDATE, 0);

SELECT * FROM REVIEW;

DROP TABLE REVIEW;


-- 글 테이블 -- 
CREATE TABLE WRITING(
WRI_NO NUMBER PRIMARY KEY, -- 글 번호 
WRI_TITLE VARCHAR2(50) NOT NULL, -- 글 제목 
WRI_DATE DATE DEFAULT SYSDATE, -- 글 작성날짜 
USER_NO NUMBER REFERENCES USERLIST(USER_NO) ON DELETE CASCADE -- 유저(관리자) NO
);

CREATE SEQUENCE WRI_NO_SEQ NOCACHE;
DROP SEQUENCE WRI_NO_SEQ;

INSERT INTO WRITING VALUES(WRI_NO_SEQ.NEXTVAL, '강동구 TOP10', SYSDATE, 2);

SELECT * FROM WRITING;

DROP TABLE WRITING;


-- 글 상세 테이블 -- 
CREATE TABLE WRILIST(
WRILIST_NO NUMBER PRIMARY KEY, -- 글상세 NO 
WRI_NO NUMBER REFERENCES WRITING(WRI_NO) ON DELETE CASCADE, -- 글 NO 
RES_NO NUMBER REFERENCES RESTAURANT(RES_NO) ON DELETE CASCADE, -- 식당 NO 
WRI_CONTENT VARCHAR2(500) NOT NULL -- 글상세 내용(각 식당별?) 
);

CREATE SEQUENCE WRILIST_NO_SEQ NOCACHE;
DROP SEQUENCE WRILIST_NO_SEQ;

INSERT INTO WRILIST VALUES(WRILIST_NO_SEQ.NEXTVAL, 1, 2, '좋아요');
INSERT INTO WRILIST VALUES(WRILIST_NO_SEQ.NEXTVAL, 1, 3, '음~');

SELECT * FROM WRILIST;

DROP TABLE WRILIST;


-- 공지사항 테이블 --
CREATE TABLE NOTICE(
NOTI_NO NUMBER PRIMARY KEY, -- 공지사항 NO 
USER_NO NUMBER REFERENCES USERLIST(USER_NO) ON DELETE CASCADE, --유저NO
NOTI_TITLE VARCHAR2(50) NOT NULL, -- 공지사항 제목 
NOTI_DATE DATE DEFAULT SYSDATE, -- 공지사항 작성날짜 
NOTI_CONTENT VARCHAR2(500) NOT NULL, -- 공지사항 내용 
NOTI_HITS NUMBER NOT NULL -- 공지사항 조회수 
);

CREATE SEQUENCE NOTI_NO_SEQ  NOCACHE;
DROP SEQUENCE NOTI_NO_SEQ;

INSERT INTO NOTICE VALUES(NOTI_NO_SEQ.NEXTVAL, 2, '강퇴목록', SYSDATE, '경으니', 0);

SELECT * FROM NOTICE;

DELETE FROM NOTICE WHERE NOTI_NO = 1;

DROP TABLE NOTICE;